// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCBbh3SlQ7KskvSu2cU7Gdl6jX2mU2t7I',
    appId: '1:840987184360:web:cabbc0f1d7d6e1dafa0d5d',
    messagingSenderId: '840987184360',
    projectId: 'flutterlcobootcamp-ce073',
    authDomain: 'flutterlcobootcamp-ce073.firebaseapp.com',
    storageBucket: 'flutterlcobootcamp-ce073.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ux-y2-HMOM4XyEJ8CGCAf0McXJLJXJw',
    appId: '1:840987184360:android:dac29b16a84e9e3efa0d5d',
    messagingSenderId: '840987184360',
    projectId: 'flutterlcobootcamp-ce073',
    storageBucket: 'flutterlcobootcamp-ce073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdiiiy7_OtxxxIH1vSpCwmcikrTcIOiFg',
    appId: '1:840987184360:ios:e190fc31f90dce55fa0d5d',
    messagingSenderId: '840987184360',
    projectId: 'flutterlcobootcamp-ce073',
    storageBucket: 'flutterlcobootcamp-ce073.appspot.com',
    iosClientId: '840987184360-ijiqk8ki10fnnm2relspotf9trflpoj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdiiiy7_OtxxxIH1vSpCwmcikrTcIOiFg',
    appId: '1:840987184360:ios:e190fc31f90dce55fa0d5d',
    messagingSenderId: '840987184360',
    projectId: 'flutterlcobootcamp-ce073',
    storageBucket: 'flutterlcobootcamp-ce073.appspot.com',
    iosClientId: '840987184360-ijiqk8ki10fnnm2relspotf9trflpoj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselogin',
  );
}
